bugfix: sym file parser passes invalid type for dbc_specifics
caused exception when trying to convert a sym file to a dbc file:

Traceback (most recent call last):
  File "cantools/cantools/__init__.py", line 81, in _main
    args.func(args)
  File "cantools/cantools/subparsers/convert.py", line 14, in _do_convert
    encoding=args.encoding)
  File "cantools/cantools/database/__init__.py", line 216, in dump_file
    output = database.as_dbc_string()
  File "cantools/cantools/database/can/database.py", line 283, in as_dbc_string
    self._dbc))
  File "cantools/cantools/database/can/formats/dbc.py", line 1631, in dump_string
    val_table = _dump_value_tables(database)
  File "cantools/cantools/database/can/formats/dbc.py", line 481, in _dump_value_tables
    for name, choices in database.dbc.value_tables.items():
AttributeError: 'list' object has no attribute 'value_tables'

I have fixed this by not passing an argument to this parameter
as it is also done in arxml.py and kcd.py.
The default value is None, see cantools/cantools/database/can/internal_database.py