monitor: fix crash when filter_regex is None from argparse by default
 $ cantools -d monitor -i socketcan tests/files/dbc/motohawk.dbc

  ... press f

    Monitor(stdscr, args).run()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "cantools/subparsers/monitor.py", line 109, in run
    self.tick(max_num_keys_per_tick)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "cantools/subparsers/monitor.py", line 121, in tick
    self.process_user_input(max_num_keys)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "cantools/subparsers/monitor.py", line 247, in process_user_input
    self.process_user_input_menu(key)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "cantools/subparsers/monitor.py", line 271, in process_user_input_menu
    self._filter_cursor_pos = len(self._filter)
                              ~~~^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()