monitor: fix crash while decoding message with bad length
Decoding message with bad length (and using --no-strict) raises
exception in decoding that is caught in format_message and returned as a
string that causes uncaught exception when --single-line is not used:

$ ip link add dev vcan0 type vcan
$ ip link set up vcan0
$ cantools -d monitor -c vcan0 tests/files/dbc/bad_message_length.dbc --no-strict
  File "monitor.py", line 540, in update
    modified = self.update_messages()
  File "monitor.py", line 531, in update_messages
    self.try_update_message()
  File "monitor.py",line 417, in try_update_message
    formatted = [f'{timestamp:12.3f}  {lines[1]}']
IndexError: list index out of range
$ cansend vcan0 001#11

This patch handles all decoding exceptions directly in monitor in a
single place.