more typing
I am using Any instead of ElementTree.Element in arxml.py
to avoid a bunch of mypy errors like
cantools/database/can/formats/arxml.py:1794: error: Item "None" of "Optional[Element]" has no attribute "iterfind"