dump takes sort_signals function instead of reverse_signals [WIP]
continuation of commit a802630078421a75fd12d9ce9a931bc2c81f2379

how do I satisfy mypy?
$ mypy cantools
cantools/database/can/message.py:73: error: "Literal['default']" not callable
cantools/database/can/formats/kcd.py:438: error: Incompatible default for argument "sort_signals" (default has type "object", argument has type "Union[Callable[[List[Signal]], List[Signal]], Literal['default'], None]")
cantools/database/can/formats/dbc.py:1665: error: Incompatible default for argument "sort_signals" (default has type "object", argument has type "Union[Callable[[List[Signal]], List[Signal]], Literal['default'], None]")
cantools/database/can/database.py:313: error: Incompatible default for argument "sort_signals" (default has type "object", argument has type "Union[Callable[[List[Signal]], List[Signal]], Literal['default'], None]")
cantools/database/can/database.py:327: error: Incompatible default for argument "sort_signals" (default has type "object", argument has type "Union[Callable[[List[Signal]], List[Signal]], Literal['default'], None]")
Found 5 errors in 4 files (checked 47 source files)