sort_signals is function instead of bool [WIP]
$ mypy cantools
cantools/database/__init__.py:96: error: Argument 5 to "load" has incompatible type "Optional[Callable[[List[Signal]], None]]"; expected "bool"
Found 1 error in 1 file (checked 47 source files)

why??